mysite/diet/urls.py
from django.urls import path, include
from . import views
from .views import HomeView, MealList, MealsListByDay, AddMealView, UpdateMealView, DeleteMealView

app_name= 'diet'

urlpatterns = [
    path('', HomeView.as_view(), name= 'home'),
    path('diet/', include([
        path('<int:year>/<str:month>/', HomeView.as_view(), name= 'home'),
        path('<int:year>/<str:month>/<int:day>/', MealsListByDay.as_view(), name='meals-by-day'),
        path('<int:year>/<str:month>/<int:day>/update_meal/<int:pk>', UpdateMealView.as_view(), name='update-meal'),
        path('<int:year>/<str:month>/<int:day>/add_meal/', AddMealView.as_view(), name='add-meal'),
        path('<int:year>/<str:month>/<int:day>/delete_meal/<int:pk>', DeleteMealView.as_view(), name='delete-meal'),
        path('meal_list', MealList.as_view(), name='meal-list'),]
    ))
] 

mysite/members/urls.py
from django.urls import path, include
from . import views
from .views import LoginUserView, Useregister
from django.contrib.auth.views import LogoutView 

app_name= 'members'

urlpatterns = [
    path('login/', LoginUserView.as_view(), name= 'login_user'),
    path('logout/', LogoutView.as_view(), name= 'logout_user'),
    path('register/', Useregister.as_view(), name= 'register'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diet.urls', namespace='diet')),
    path('members/', include("django.contrib.auth.urls")),
    path('members/', include('members.urls', namespace='members')),
]

mysite/diet/models.py
from django.db import models
from django.forms import ModelForm
from django import forms
from datetime import datetime
from django.utils.safestring import mark_safe

MEAL_CHOICES=[
    ('Breakfast', 'Breakfast'),
    ('Brunch', 'Brunch'),
    ('Lunch', 'Lunch'),
    ('Dinner', 'Dinner'),
    ('Dessert', 'Dessert'),
    ('Midnight Snack', 'Midnight Snack')
]
class Meal(models.Model):
    name= models.CharField(default= None,  max_length=20)
    date= models.DateField(default=datetime.today().date())
    meal= models.CharField(max_length=20, choices=MEAL_CHOICES, default='Breakfast')
    food_name= models.CharField(max_length=60)
    calorie= models.IntegerField(help_text='The unit is kcal')
    location= models.CharField(max_length=50, help_text='Enter the place you buy the food.')

    def __str__(self):
        return f'{self.date} {self.meal}'

class CalorieChart(models.Model):
    food_name= models.CharField(max_length=60)
    calorie= models.IntegerField()

    def __str__(self):
        return f'{self.food_name} {self.calorie}'

mysite/diet/forms.py
from django import forms
from django.forms import ModelForm
from .models import Meal
from datetime import datetime

# Create MealForm
class MealModelForm(ModelForm):
    
    class Meta:
        model= Meal
        fields= ['date', 'meal', 'food_name', 'calorie', 'location']

        widgets={
            'date':forms.SelectDateWidget(attrs={'class':'form-control'}),
            'meal':forms.Select(attrs={'class':'form-control'}),
            'calorie':forms.NumberInput(attrs={'class':'form-control'}),
            'food_name':forms.TextInput(attrs={'class':'form-control'}),
            'location':forms.TextInput(attrs={'class':'form-control'})
        }
    
    def __init__(self,  *args, **kwargs):
        self.year= kwargs.pop('year')
        self.month= kwargs.pop('month')
        self.day= kwargs.pop('day')
        super(MealModelForm, self).__init__(*args, **kwargs)
        self.fields['date'].initial= datetime.strptime(f'{self.year}-{self.month}-{self.day}', "%Y-%B-%d")

mysite/diet/views.py
import calendar
from datetime import datetime, timedelta
from django.shortcuts import  redirect
from django.urls import reverse_lazy
from .forms import MealModelForm
from .models import Meal
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.db import connection
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

@method_decorator(login_required, name='dispatch')
class HomeView(TemplateView):
    template_name= 'diet/home.html'

    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)

        username= self.request.user.get_username()
        year= context.get('year') if context.get('year') else datetime.now().year
        month= context.get('month') if context.get('year') else datetime.now().strftime('%B')

        days_list= []
        tmp= []
        list_months= list(calendar.month_name)
        month_num= list_months.index(month)
        for d in calendar.Calendar(firstweekday=6).itermonthdays(year, month_num):
            if len(tmp) == 7:
                days_list.append(tmp)
                tmp= []
            tmp.append('' if d == 0 else d)
        days_list.append(tmp)

        # Set the value for previous an next button
        pre_mn, pre_yr= (list_months[12], year -1) if month_num -1 < 1 else (list_months[month_num-1], year)
        nxt_mn, nxt_yr= (list_months[1], year +1) if month_num +1 > 12 else (list_months[month_num+1], year)

        context.update({'username': username, 'year': year, 'month': month, 
                        'month_num':month_num,'days_list': days_list,
                        'pre_mn':pre_mn, 'pre_yr':pre_yr,
                        'nxt_mn':nxt_mn, 'nxt_yr':nxt_yr,
                        })
        return context

# Change format of date
def DateTransfer(kwargs):
    year= kwargs['year']
    month= list(calendar.month_name).index(kwargs['month'])
    day= int(kwargs['day'])

    return year, month, day

# Get weekrange from given date
# def WeekRange(date:datetime.date):

#     start_date= (date - timedelta(days= date.weekday())).date()
#     end_date= (start_date + timedelta(days= 6))

#     return start_date, end_date

# Transfer sql date into Queryset-like form
def DictFetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

class MealsListByDay(ListView):
    model= Meal
    template_name= 'diet/meals-by-day.html' 

    def get_queryset(self, *args, **kwargs):
        year, month, day= DateTransfer(self.kwargs)
        date= datetime(year, month, day).date().strftime('%Y-%m-%d')
        queries= {'date': date, 'username': self.request.user.get_username()}
        with connection.cursor() as cursor:
            cursor.execute("With rank_table AS\
                (SELECT *, RANK() OVER (\
                    PARTITION BY date >= date_trunc('week', %(date)s::date), \
                        date < date_trunc('week', %(date)s::date) + INTERVAL '7 days' ORDER BY calorie DESC) as rank FROM diet_meal)\
                    SELECT * FROM rank_table WHERE date= %(date)s and name = %(username)s",
                    params= queries)
            queryset= DictFetchall(cursor)
        return queryset

    def get_context_data(self, **kwargs):
        year, month, day= DateTransfer(self.kwargs)
        context= super().get_context_data(**kwargs)
        context['date']= datetime(year, month, day).strftime("%Y-%B-%d")
        para_dict= {'year': year, 'month': self.kwargs['month'], 'day': day}
        context.update(para_dict)
        return context

class AddMealView(CreateView):
    form_class= MealModelForm
    template_name= 'diet/add-meal.html'
    
    def get(self, request, *args, **kwargs):
        form = self.form_class(**kwargs)
        return self.render_to_response({'form': form})

    def post(self, *args, **kwargs):
        form= self.form_class(self.request.POST, **kwargs)
        if form.is_valid(): 
            form.instance.name = self.request.user.get_username()
            form.save()
            messages.success(self.request, 'Congrats!! You have updated your diet.')
            return redirect(self.get_success_url())
        else:
            messages.error(self.request, 'There is something wrong with your new diet. ...')
            return self.form_invalid(form)

    def get_success_url(self):
        return reverse_lazy('diet:meals-by-day', kwargs= self.kwargs)

class UpdateMealView(UpdateView):
    form_class= MealModelForm
    template_name= 'diet/update-meal.html'
    queryset= Meal.objects.all()

    def get(self, request, *args, **kwargs):
        pk= kwargs.pop('pk')
        meal= Meal.objects.get(pk= pk)
        form = self.form_class(**kwargs, instance= meal)
        return self.render_to_response({'form': form})
    
    def post(self, request, *args, **kwargs):
        pk= kwargs.pop('pk')
        meal= Meal.objects.get(pk= pk)
        form= self.form_class(request.POST, **kwargs, instance= meal)
        if form.is_valid():
            form.save()
            messages.success(self.request, 'Congrats!! You have updated your diet.')
            return redirect(self.get_success_url())
        else:
            messages.error(request, 'There is an error updating the diet.')
            return self.form_invalid(form)

    def get_success_url(self):
        self.kwargs.pop('pk')
        return reverse_lazy('diet:meals-by-day', kwargs= self.kwargs)

class DeleteMealView(DeleteView):
    model= Meal
    template_name= 'diet/delete-meal.html'

    def get_success_url(self):
        self.kwargs.pop('pk')
        return reverse_lazy('diet:meals-by-day', kwargs= self.kwargs)
    
@method_decorator(login_required, name='dispatch')
class MealList(ListView):
    model= Meal
    template_name= 'diet/meal-list.html'
    paginate_by= 50
    
    
    def get_queryset(self):
        queryset= self.model.objects.filter(name= self.request.user.get_username())
        # queryset= self.model.objects.raw('SELECT * FROM diet_meal WHERE name = %s', [self.request.user.get_username()])
        start_date= self.request.GET.get('start_date')
        end_date= self.request.GET.get('end_date')
        meal= self.request.GET.get('meal')
        food_name= self.request.GET.get('food_name')
        location= self.request.GET.get('location')
        q= Q()
        if start_date:
            q &= Q(date__gte=start_date)
        if end_date:
            q &= Q(date__lte=end_date)
        if meal:
            q &= Q(meal__contains=meal)
        if food_name:
            q &= Q(food_name__contains=food_name)
        if location:
            q &= Q(location__contains= location)
        queryset= queryset.filter(q)
        return queryset

    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context['object_list']= self.get_queryset()
        return context

# function-based view
# def MealsByDay(request, *args, **kwargs):
#     year, month, day= GenerDate(kwargs)
#     date= datetime(year, month, day).strftime("%Y-%B-%d")
#     meals= Meal.objects.filter(date=datetime(year, month, day).date())
    
#     return render(request, 'diet/meals-by-day.html', 
#                     {'meals': meals,'year': year, 'month': list(calendar.month_name)[month], 'day':day
#                     ,'date': date })

# def AddMeal(request, *args, **kwargs):
#     if request.method == 'POST':
#         form= MealModelForm(request.POST, **kwargs)
#         form.save()
#         messages.success(request, 'Congrats!! You have updated your diet.')
#         return redirect(reverse('diet:meals-by-day', kwargs=kwargs))
#     else:     
#         form= MealModelForm(**kwargs)
#     return render(request, 'diet/add-meal.html', {'form': form})

# def UpdateMeal(request, *args, **kwargs):
#     id_= kwargs.pop('pk')
#     meal= Meal.objects.get(pk= id_)
#     form= MealModelForm(request.POST or None, **kwargs, instance= meal)
#     if form.is_valid():
#         form.save()
#         return redirect(reverse('diet:meals-by-day', kwargs= kwargs))
#     return render(request, 'diet/update-meal.html', {'form': form, 'k':kwargs})

# def DeleteMeal(request, *args, **kwargs):
#     id_= kwargs.pop('pk')
#     meal= Meal.objects.get(pk= id_)
#     messages.warning(request, 'You have deleted an meal record!')
#     meal.delete()
#     return redirect(reverse('diet:meals-by-day', kwargs= kwargs))

mysite/diet/templates/diet/add-meal.html
{% extends 'diet/base.html' %}

{% block head %}
{% endblock %}

{% block content %}

<div class="container pt-md-5">
    <h3>Add meals</h3>
    <div class="row">
        <div class="col-md-4">
        <form action="" method="POST">
            {% csrf_token%}
            
            {{ form.as_p }}


            <button type="submit" class="btn btn-primary">
                Add meal</button>

        </form>
        </div>
    </div>
</div>
{% endblock %}

mysite/diet/templates/diet/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    

    <title>Diet Tracker</title>
    {% block head %} {% endblock %}
  </head>
  <body>
    {% include 'diet/navbar.html' %}
    {% include 'diet/messages.html'  %}

    {% block content %} {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- add font-awesome -->
    <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css" 
    rel="stylesheet"  type='text/css'>

    <!-- add for datepicker -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <!-- <link rel="stylesheet" href="//resources/demos/style.css"> -->
    <script src="https://code.jquery.com/jquery-3.6.4.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script>
    $( function() {
      $( "#start_date" ).datepicker({ dateFormat: 'yy-mm-dd' , minDate: "-1y", maxDate: 0, showOtherMonths: true, });
      $( "#end_date" ).datepicker({ dateFormat: 'yy-mm-dd', minDate: "-1y", maxDate: 0, showOtherMonths: true, });
      $( "#calendar" ).datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: 'MM yy',
        beforeShow: function(input) {
          $(input).datepicker("widget").addClass('hide-calendar');
        },
        onClose: function(dateText, inst) {
          $(this).datepicker('setDate', new Date(inst.selectedYear, inst.selectedMonth, 1));
          
        }
      }
      )
      $( "#calendar" ).datepicker('setDate', new Date())
    } );
    </script>
    <style>
    .hide-calendar .ui-datepicker-calendar {
        display: none;
    }
    </style>
    

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

mysite/diet/templates/diet/delete-meal.html
{% extends 'diet/base.html' %}

{% block head %}
{% endblock %}

{% block content %}
{{ k }}
    <div class="container pt-md-5">
        <div class="row">
            <div class="col-md-4">
            <form action="" method="POST">
                {% csrf_token%}
                <p>Are you sure you want to delete "{{ object }}"?</p>
                
                {{ form }}

                <button type="submit" class="btn btn-primary">
                    Confirm</button>

            </form>
        </div>
    </div>
{% endblock %}

mysite/diet/templates/diet/home.html
{% extends 'diet/base.html' %}

{% block head %}
{% endblock %}

{% block content %}
<div class="container pt-md-5">
    <div class="card text-dark bg-light mb-3">
        <div class="card-body fs-5 fw-bold">
            Hello, {{ username }}. Welcome back to Diet-Tracker. Keep going on taking down your daily meals!!!
        </div>
    </div>
    <div class="d-flex justify-content-between">
        <div><a class="btn-sm btn-outline-secondary" href="{% url 'diet:home' pre_yr pre_mn %}">&lsaquo;Previous</a></div>
        <div class="fs-4"> {{ month }} {{ year }}
        </div>        
        <div><a class="btn-sm btn-outline-secondary" href="{% url 'diet:home' nxt_yr nxt_mn %}" >Next&rsaquo;</a></div>
    </div>
    <table class="table table-light table-bordered">
        </tr>
        <tr class="col-1">
            <th>Sun</th>
            <th>Mon</th>
            <th>Tue</th>
            <th>Wed</th>
            <th>Thu</th>
            <th>Fri</th>
            <th>Sat</th>
        </tr>
        {% for days in days_list %}
        <tr class="col-1">
            {% for day in days %}
            {% if day != '' %}
            <td><a href="{% url 'diet:meals-by-day' year month day %}" class="text-decoration-none text-dark">{{ day }}</a>
            </td>
            {% else %}
            <td>{{ day }}</td>
            {% endif %}
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
    <div class="card border-secondary mb-3">
        <div class="card-header">
            Instructions
        </div>
        <div class="card-body fs-7">
            You can pick up the date you want to add/ update meals, and also view all/ filtered meals on Meals history page.
            <!-- <form method="GET">
                <input type="text" id="calendar" name="cal" style="text-align: center;" >
                <button class="btn-sm btn-outline-primary">Submit</button>
            </form> -->
        </div>
    </div>
</div>
{% endblock %}

mysite/diet/templates/diet/meal-list.html
{% extends 'diet/base.html' %}

{% block head %}
{% endblock %}

{% block content %}
{% include 'diet/search-meal.html' %}

<div class="container pt-md-1">
<table class="table table-sm table-bordered text-center">
    <thead>
      <tr class="table-info">
        <th scope="col" class="col-1"></th>
        <th scope="col" class="col-2">Date</th>
        <th scope="col" class="col-2">Meal</th>
        <th scope="col" class="col-2">Food name</th>
        <th scope="col" class="col-2">Calorie</th>
        <th scope="col" class="col-2">Location</th>
    </thead>
    <tbody>
        {% if user.is_authenticated %}
            {% if object_list %}
                {% for meal in object_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ meal.date|date:"o-m-d" }}</td>
                    <td>{{ meal.meal }}</td>
                    <td>{{ meal.food_name }}</td>
                    <td>{{ meal.calorie }}</td>
                    <td>{{ meal.location }}</td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                <td style="text-align: center ;" colspan="6">No meal available...</td>
                </tr>
            {% endif %}
        {% else %}
                <tr>
                <td style="text-align: center ;" colspan="6">No meal available...</td>
                </tr>
        {% endif %}
        <input name="next" type="hidden" value="{% url 'diet:home' %}">
    </tbody>
</table>
</div>
{% endblock %}

mysite/diet/templates/diet/meals-by-day.html
{% extends 'diet/base.html' %}

{% block head %}

{% endblock %}

{% block content %}
    <div class="container pt-md-5">
        <div class="d-flex justify-content-between">
            <strong> <h4>{{ date }}</h4> </strong>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group">
                    <a class="btn btn-outline-primary" href="{% url 'diet:add-meal' year month day %}">
                        Add Meal</a>
                </div>
            </div>
        </div>
        <br> 
          <table class="table table-sm table-bordered text-center">
            <thead style="background-color: lightcyan;">
              <tr>
                <th scope="col" class="col-2">Meal</th>
                <th scope="col" class="col-2">Food_name</th>
                <th scope="col" class="col-2">Location</th>
                <th scope="col" class="col-2">Calorie</th>
                <th scope="col" class="col-2">Weekly calorie rank</th>
                <th scope="col" class="col-1">action</th>
              </tr>
            </thead>
            <tbody>
            {% if not object_list %}
              <tr>
                <td style="text-align: center ;" colspan="6">No meal available...</td>
              </tr>
            {% endif %}

            {% for meal in object_list %}
              <tr>
                <td>{{ meal.meal }}</td>
                <td>{{ meal.food_name }}</td>
                <td>{{ meal.location }}</td>
                <td>{{ meal.calorie }}</td>
                <td>{{ meal.rank }}</td>
                <th scope="col">
                  <a href="{% url 'diet:update-meal' year month day meal.id %}" class="text-decoration-none">
                    <button type="button" class="btn btn-sm btn-outline-secondary">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                      </svg>
                    </button>
                  </a>
                  <a href="{% url 'diet:delete-meal' year month day meal.id %}">
                    <button type="button" class="btn btn-sm btn-outline-danger" class="text-decoration-none">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                        <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"></path>
                      </svg>
                    </button>
                  </a>
                </th>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          
    </div>
{% endblock %}

mysite/diet/templates/diet/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
{% endif %}

mysite/diet/templates/diet/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Diet</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'diet:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'diet:meal-list' %}">Meals history</a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" aria-current="page" href="#">Calorie chart</a>
          </li> -->

          <!--
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
          -->
        </ul>
        <div class="text-end text-decoration-none">
          <ul class="navbar-nav">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link px-2" aria-current="page" href="{% url 'members:logout_user' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'members:login_user' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'members:register' %}">Sign up</a>
            </li>
          {% endif %}
          </ul>
        </div>
        <!-- <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form> -->
      </div>
    </div>
  </nav>

mysite/diet/templates/diet/update-meal.html
{% extends 'diet/base.html' %}

{% block head %}
{% endblock %}

{% block content %}
    <div class="container pt-md-5">
        <div class="row">
            <div class="col-md-4">
            <form action="" method="POST">
                {% csrf_token%}
                
                {{ form.as_p }}

                <button type="submit" class="btn btn-primary">
                    Update</button>

            </form>
        </div>
    </div>
{% endblock %}